server:
  port: 8091

spring:
  application:
    name: cloud-auth-authorization-service #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://www.lirongblog.com:3306/cloud_user_center?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: ABCDlirong#801
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://${security.config.username}:${security.config.password}@local.eureka6001.com:6001/eureka,http://${security.config.username}:${security.config.password}@local.eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址

security:
  config:
    username: gtppoplp
    password: ABCDlirong801
  oauth2:
    jwt:
      signingKey: 123456
    client:
      #配置应用信息
      client-id: admin
      client-secret: 123456
