CREATE TABLE sup_supplier
(
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    classes             TINYINT(1)   DEFAULT 0  NOT NULL COMMENT '类别(1/国有,2/私营,3/个体,4/其它)',
    name                VARCHAR(64)  DEFAULT '' NOT NULL COMMENT '名称',
    alias               VARCHAR(48)  DEFAULT '' NOT NULL COMMENT '简称',
    contacts            VARCHAR(24)  DEFAULT '' NOT NULL COMMENT '联系人',
    phone               VARCHAR(24)  DEFAULT '' NOT NULL COMMENT '联系方式',
    teamwork_at         BIGINT       DEFAULT 0  NOT NULL COMMENT '合作时间',
    employee            INT          DEFAULT 0  NOT NULL COMMENT '员工人数',
    type                TINYINT(3)   DEFAULT 0  NOT NULL COMMENT '类型(1/原料,2/OEM,3/包材)',
    supply_period       VARCHAR(64)  DEFAULT '' NOT NULL COMMENT '供货期',
    production_card     VARCHAR(64)  DEFAULT '' NOT NULL COMMENT '生产证号',
    visit_rate          VARCHAR(255) DEFAULT '' NOT NULL COMMENT '现场拜访评定',
    visit_at            BIGINT(20)   DEFAULT 0  NOT NULL COMMENT '现场拜访评定时间',
    cooperation_rate    VARCHAR(255) DEFAULT '' NOT NULL COMMENT '合作过程评定',
    cooperation_at      INT          DEFAULT 0  NOT NULL COMMENT '合作过程评定时间',
    rate                VARCHAR(255) DEFAULT '' NOT NULL COMMENT '综合评定',
    rate_at             INT          DEFAULT 0  NOT NULL COMMENT '综合评定时间',
    quality_rate        VARCHAR(255) DEFAULT '' NOT NULL COMMENT '质量控制评定',
    factory_address     VARCHAR(255) DEFAULT '' NOT NULL COMMENT '工厂地址',
    ware_address        VARCHAR(255) DEFAULT '' NOT NULL COMMENT '仓库地址',
    business_scope      VARCHAR(255) DEFAULT '' NOT NULL COMMENT '经营范围',
    business_type       VARCHAR(255) DEFAULT '' NOT NULL COMMENT '经营类别',
    acting_brand        VARCHAR(255) DEFAULT '' NOT NULL COMMENT '代理品牌',
    featured_products   VARCHAR(255) DEFAULT '' NOT NULL COMMENT '主营优势产品',
    rd_team             TINYINT(3)   DEFAULT 2  NOT NULL COMMENT '研发团队(0/无,1/有,2/未知)',
    teams               INT          DEFAULT 0  NOT NULL COMMENT '团队人数',
    machine             VARCHAR(255) DEFAULT '' NOT NULL COMMENT '机器及乳化设备',
    cooperation_brand   VARCHAR(255) DEFAULT '' NOT NULL COMMENT '合作品牌',
    cooperation_packing VARCHAR(255) DEFAULT '' NOT NULL COMMENT '合作包材',
    texture             VARCHAR(128) DEFAULT '' NOT NULL COMMENT '材质',
    equipment           VARCHAR(255) DEFAULT '' NOT NULL COMMENT '设备',
    factory_area        INT          DEFAULT 0  NOT NULL COMMENT '产房面积/平方米',
    peoples             INT          DEFAULT 0  NOT NULL COMMENT '生产人数',
    production_line     INT          DEFAULT 0  NOT NULL COMMENT '生产线',
    monthly_output      VARCHAR(24)  DEFAULT '' NOT NULL COMMENT '月产量',
    cart                TINYINT(3)   DEFAULT 2  NOT NULL COMMENT '货车(0/无,1/有,2/未知)',
    own_brand           VARCHAR(24)  DEFAULT '' NOT NULL COMMENT '自有品牌',
    production_license  VARCHAR(128) DEFAULT '' NOT NULL COMMENT '生产许可证',
    status              TINYINT(3)   DEFAULT 0  NOT NULL COMMENT '状态(0/合作,1/冻结,2/淘汰)',
    is_delete           TINYINT(1)   DEFAULT 0  NULL COMMENT '是否删除(0否,null是)',
    created_id          INT          DEFAULT 0  NOT NULL COMMENT '创建人id',
    created_by          VARCHAR(32)  DEFAULT '' NOT NULL COMMENT '创建人',
    created_at          INT          DEFAULT 0  NOT NULL COMMENT '创建时间',
    updated_by          VARCHAR(32)  DEFAULT '' NOT NULL COMMENT '修改人',
    updated_at          INT          DEFAULT 0  NOT NULL COMMENT '修改时间',
    dept_id             INT          DEFAULT 0  NOT NULL COMMENT '部门id',
    dept_name           VARCHAR(64)  DEFAULT '' NOT NULL COMMENT '部门名称',
    teamwork_end        INT          DEFAULT 0  NOT NULL COMMENT '合作结束时间'
) COMMENT '供应商' COLLATE = utf8_unicode_ci;

