server:
  port: 5001
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git: # 远程库的git地址
          uri: https://github.com/gtppoplp/cloud-config.git
          username: gtppoplp@outlook.com
          password: lirong801
          search-paths: # 设置配置文件查找的匹配目录
            - auth
            - center
            - gateway
            - services/provider
            - services/consumer
          default-label: test #默认分支
  rabbitmq:
    host: www.lirongblog.com
    port: 5672
    username: guest
    password: lirong801
# 暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh